parameters:
  osName: ''
  testFramework: ''
  configuration: ''

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host $(AnotherEnvVar); Write-Host $(PipeLineUIVar)' 

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:Build /p:Configuration=${{ parameters.configuration }};TestFramework=${{ parameters.testFramework }};PullRequestNumber=$(System.PullRequest.PullRequestNumber)'

- template: publish-artifacts-steps.yml
  parameters:
    artifactName: build-${{ parameters.osName }}