variables:
  WindowsName: windows
  WindowsImage: vs2017-win2016
  LinuxName: linux
  LinuxImage: ubuntu-18.04
  MacOSName: macOS
  MacOSImage: macOS-10.13
  TestFramework: netcoreapp2.2
  TestTarget: Test
  Configuration: Debug
  AnotherEnvVar: true

jobs:
- job: Build
  displayName: Build
  condition: succeeded()
  strategy:
    matrix:
      windows:
        OSName: ${{ variables.WindowsName }}
        ImageName: ${{ variables.WindowsImage }}
      linux:
        OSName: ${{ variables.LinuxName }}
        ImageName: ${{ variables.LinuxImage }}
      macOS:
        OSName: ${{ variables.MacOSName }}
        ImageName: ${{ variables.MacOSImage }}
  pool:
    vmImage: $(ImageName)

  steps:
  - template: util/build-steps.yml
    parameters:
      osName: $(OSName)
      testFramework: ${{ variables.TestFramework }}
      configuration: ${{ variables.Configuration }}
