// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Aks.Models
{
    using System.Collections.Generic;
    using Microsoft.Rest;

    /// <summary>
    /// The list of available upgrades for compute pools.
    /// </summary>
    [Rest.Serialization.JsonTransformation]
    public partial class PSManagedClusterUpgradeProfile
    {
        /// <summary>
        /// Gets id of upgrade profile.
        /// </summary>
        public string Id { get; private set; }

        /// <summary>
        /// Gets name of upgrade profile.
        /// </summary>
        public string Name { get; private set; }

        /// <summary>
        /// Gets type of upgrade profile.
        /// </summary>
        public string Type { get; private set; }

        /// <summary>
        /// Gets or sets the list of available upgrade versions for the control
        /// plane.
        /// </summary>
        public PSManagedClusterPoolUpgradeProfile ControlPlaneProfile { get; set; }

        /// <summary>
        /// Gets or sets the list of available upgrade versions for agent
        /// pools.
        /// </summary>
        public IList<PSManagedClusterPoolUpgradeProfile> AgentPoolProfiles { get; set; }
    }
}
