// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Aks.Models
{
    /// <summary>
    /// AADProfile specifies attributes for Azure Active Directory integration.
    /// </summary>
    public partial class PSManagedClusterAadProfile
    {
        /// <summary>
        /// Gets or sets the client AAD application ID.
        /// </summary>
        public string ClientAppID { get; set; }

        /// <summary>
        /// Gets or sets the server AAD application ID.
        /// </summary>
        public string ServerAppID { get; set; }

        /// <summary>
        /// Gets or sets the server AAD application secret.
        /// </summary>
        public string ServerAppSecret { get; set; }

        /// <summary>
        /// Gets or sets the AAD tenant ID to use for authentication. If not
        /// specified, will use the tenant of the deployment subscription.
        /// </summary>
        public string TenantID { get; set; }
    }
}
