// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Aks.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Managed cluster Access Profile.
    /// </summary>
    [Rest.Serialization.JsonTransformation]
    public partial class PSManagedClusterAccessProfile : PSResource
    {
        /// <summary>
        /// Gets or sets base64-encoded Kubernetes configuration file.
        /// </summary>
        public byte[] KubeConfig { get; set; }

    }
}
