// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Aks.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Access profile for managed cluster API server.
    /// </summary>
    public partial class PSManagedClusterAPIServerAccessProfile
    {
        /// <summary>
        /// Gets or sets authorized IP Ranges to kubernetes API server.
        /// </summary>
        public IList<string> AuthorizedIPRanges { get; set; }

        /// <summary>
        /// Gets or sets whether to create the cluster as a private cluster or
        /// not.
        /// </summary>
        public bool? EnablePrivateCluster { get; set; }

    }
}
