// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Aks.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Desired outbound IP resources for the cluster load balancer.
    /// </summary>
    public partial class PSManagedClusterLoadBalancerProfileOutboundIPs
    {
        /// <summary>
        /// Gets or sets a list of public IP resources.
        /// </summary>
        public IList<PSResourceReference> PublicIPs { get; set; }

    }
}
