// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Aks.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PSManagedClusterPoolUpgradeProfileUpgradesItem
    {
        /// <summary>
        /// Gets or sets kubernetes version (major, minor, patch).
        /// </summary>
        public string KubernetesVersion { get; set; }

        /// <summary>
        /// Gets or sets whether Kubernetes version is currently in preview.
        /// </summary>
        public bool? IsPreview { get; set; }

    }
}
