// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Aks.Models
{
    /// <summary>
    /// Profile for Windows VMs in the container service cluster.
    /// </summary>
    public partial class PSManagedClusterWindowsProfile
    {
        /// <summary>
        /// Gets or sets the administrator username to use for Windows VMs.
        /// </summary>
        public string AdminUsername { get; set; }

        /// <summary>
        /// Gets or sets the administrator password to use for Windows VMs.
        /// </summary>
        public string AdminPassword { get; set; }
    }
}
