// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Aks.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A Kubernetes add-on profile for a managed cluster.
    /// </summary>
    public partial class PSManagedClusterAddonProfile
    {
        /// <summary>
        /// Gets or sets whether the add-on is enabled or not.
        /// </summary>
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets or sets key-value pairs for configuring an add-on.
        /// </summary>
        public IDictionary<string, string> Config { get; set; }
    }
}
