// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Aks.Models
{
    using Microsoft.Azure.Management.ContainerService.Models;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Identity for the managed cluster.
    /// </summary>
    public partial class PSManagedClusterIdentity
    {
        /// <summary>
        /// Gets the principal id of the system assigned identity which is used
        /// by master components.
        /// </summary>
        public string PrincipalId { get; private set; }

        /// <summary>
        /// Gets the tenant id of the system assigned identity which is used by
        /// master components.
        /// </summary>
        public string TenantId { get; private set; }

        /// <summary>
        /// Gets or sets the type of identity used for the managed cluster.
        /// Type 'SystemAssigned' will use an implicitly created identity in
        /// master components and an auto-created user assigned identity in MC_
        /// resource group in agent nodes. Type 'None' will not use MSI for the
        /// managed cluster, service principal will be used instead. Possible
        /// values include: 'SystemAssigned', 'None'
        /// </summary>
        public PSResourceIdentityType? Type { get; set; }
    }
}
