// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Aks.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The list of available upgrade versions.
    /// </summary>
    public partial class PSManagedClusterPoolUpgradeProfile
    {
        /// <summary>
        /// Gets or sets kubernetes version (major, minor, patch).
        /// </summary>
        public string KubernetesVersion { get; set; }

        /// <summary>
        /// Gets or sets pool name.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets osType to be used to specify os type. Choose from
        /// Linux and Windows. Default to Linux. Possible values include:
        /// 'Linux', 'Windows'
        /// </summary>
        public string OsType { get; set; }

        /// <summary>
        /// Gets or sets list of orchestrator types and versions available for
        /// upgrade.
        /// </summary>
        public IList<PSManagedClusterPoolUpgradeProfileUpgradesItem> Upgrades { get; set; }

    }
}
