// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Aks.Models
{
    /// <summary>
    /// Reference to another subresource.
    /// </summary>
    public partial class PSSubResource
    {
        /// <summary>
        /// Gets resource ID.
        /// </summary>
        public string Id { get; private set; }

        /// <summary>
        /// Gets the name of the resource that is unique within a resource
        /// group. This name can be used to access the resource.
        /// </summary>
        public string Name { get; private set; }

        /// <summary>
        /// Gets resource type
        /// </summary>
        public string Type { get; private set; }

    }
}
